# Generated by Django 4.2.15 on 2024-10-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("student_number", models.CharField(max_length=100)),
                ("email", models.EmailField(blank=True, max_length=100, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                ("course_status", models.JSONField(blank=True, null=True)),
                (
                    "curriculum_year",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
