# Generated by Django 4.2.15 on 2024-10-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Models", "0004_alter_article_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="student_status",
            field=models.CharField(
                choices=[
                    ("Enrolled", "Enrolled"),
                    ("Graduated", "Graduated"),
                    ("Dropped", "Dropped"),
                    ("Transferred", "Transferred"),
                    ("Failed", "Failed"),
                    ("Incomplete", "Incomplete"),
                ],
                default="Enrolled",
                max_length=100,
            ),
        ),
    ]
