# Generated by Django 4.2.15 on 2024-10-28 16:17

import Models.utils.directory_helper
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Models", "0008_account_program_account_role_alter_article_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(
                blank=True,
                default="default.jpg",
                null=True,
                upload_to=Models.utils.directory_helper.get_article_media_directory,
            ),
        ),
    ]
