DEPARTMENT_CHOICES = [
    ('SCMCS', 'SCMCS'),
    ('SNAHS', 'SNAHS'),
    ('SMLS', 'SMLS'),
    ('SITHM', 'SITHM'),
    ('SASE', 'SASE'),
]

PROGRAM_CHOICES = [
    ('ABCOM', 'ABCOM'),
    ('ABMMA', 'ABMMA'),
    ('AHM', 'AHM'),
    ('BACOMM', 'BACOMM'),
    ('BARNCII', 'BARNCII'),
    ('BEED', 'BEED'),
    ('BMMA', 'BMMA'),
    ('BPP NCII', 'BPP NCII'),
    ('BSA', 'BSA'),
    ('BSAIS', 'BSAIS'),
    ('BSAT', 'BSAT'),
    ('BSB', 'BSB'),
    ('BSBA', 'BSBA'),
    ('BSC', 'BSC'),
    ('BSCS', 'BSCS'),
    ('BSE', 'BSE'),
    ('BSED', 'BSED'),
    ('BSHM', 'BSHM'),
    ('BSHRM', 'BSHRM'),
    ('BSIT', 'BSIT'),
    ('BSIT(TEST)', 'BSIT(TEST)'),
    ('BSMLS', 'BSMLS'),
    ('BSMT', 'BSMT'),
    ('BSN', 'BSN'),
    ('BSN (YIBU)', 'BSN (YIBU)'),
    ('BSNED', 'BSNED'),
    ('BSOT', 'BSOT'),
    ('BSP', 'BSP'),
    ('BSPSY', 'BSPSY'),
    ('BSPT', 'BSPT'),
    ('BSPT (YIBU)', 'BSPT (YIBU)'),
    ('BSRT', 'BSRT'),
    ('BSRT (YIBU)', 'BSRT (YIBU)'),
    ('BSTM', 'BSTM'),
    ('BSTRM', 'BSTRM'),
    ('CCNCII', 'CCNCII'),
    ('CCPIII-TAFE', 'CCPIII-TAFE'),
    ('CGNCII', 'CGNCII'),
    ('CGNCII (T)', 'CGNCII (T)'),
    ('CHSNCII', 'CHSNCII'),
    ('CTP', 'CTP'),
    ('DB', 'DB'),
    ('DBM-KENT', 'DBM-KENT'),
    ('DM', 'DM'),
    ('DMM-KENT', 'DMM-KENT'),
    ('EIMNCII', 'EIMNCII'),
    ('FBSNCII', 'FBSNCII'),
    ('FL', 'FL'),
    ('HSKNCII', 'HSKNCII'),
    ('MAP', 'MAP'),
    ('MAP (YIBU)', 'MAP (YIBU)'),
    ('MBA', 'MBA'),
    ('MBA (YIBU)', 'MBA (YIBU)'),
    ('MD', 'MD'),
    ('MD(TEST)', 'MD(TEST)'),
    ('MISICT', 'MISICT'),
    ('MSN', 'MSN'),
    ('PNCIV', 'PNCIV'),
    ('PRE-DENT', 'PRE-DENT'),
    ('SMAWNCI', 'SMAWNCI'),
    ('SMAWNCII', 'SMAWNCII'),
    ('VACOMLIT', 'VACOMLIT'),
    ('WSA', 'WSA'),
]

CURRICULUM_YEAR_CHOICES = [
        ('2016-2017', '2016-2017'),
        ('2017-2018', '2017-2018'),
        ('2018-2019', '2018-2019'),
        ('2019-2020', '2019-2020'),
        ('2020-2021', '2020-2021'),
        ('2021-2022', '2021-2022'),
        ('2022-2023', '2022-2023'),
        ('2023-2024', '2023-2024'),
        ('2024-2025', '2024-2025'),
    ]

STUDENT_STATUS_CHOICES = [ 
    ('Enrolled', 'Enrolled'),
    ('Graduated', 'Graduated'),
    ('Dropped', 'Dropped'),
    ('Transferred', 'Transferred'),
    ('Failed', 'Failed'),
    ('Incomplete', 'Incomplete'),
]


CATEGORY_CHOICES = [
    ('Events', 'Events'),
    ('Announcements', 'Announcements'),
    ('Student Activities', 'Student Activities'),
    ('General', 'General'),   
]

ROLE_CHOICES = [
    ('Student', 'Student'),
    ('Program Chair', 'Program Chair'),
    ('Dean', 'Dean'),

]